# Site settings
title: Análise de Dados
subtitle: estatísticas e probabilidades
email: gustavo.monteiro@ccc.ufcg.edu.br 
baseurl: "/postsAD" # the subpath of your site, e.g. /blog/
url: "https://GustavoDinizMonteiro.github.io/postsAD/" # the base hostname & protocol for your site
twitter_username: gutodmonteiro
github_username:  GustavoDinizMonteiro
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
