# Site settings
title: mais um site sobre
subtitle: estatísticas e outras coisas
email: gustavo.monteiro@ccc.ufcg.edu.br 
baseurl: "/maisumsitesobre" # the subpath of your site, e.g. /blog/
url: "https://GustavoDinizMonteiro.github.io/maisumsitesobre/" # the base hostname & protocol for your site
twitter_username: gutodmonteiro_
github_username:  GustavoDinizMonteiro
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
